import type { Question, MatrixItem } from './types'

const EVENTS = [
  'OX 퀴즈',
  '축구 예선/결승',
  '여성 스테이지(슈팅 다트)',
  '신입 스테이지',
  '타임어택 챌린지(8종 단체전)',
  '리더 스테이지(호핑볼 경마)',
  '파이널 계주(에어바운스 릴레이)',
  '가온 놀이동산',
]

export const DEFAULT_QUESTIONS: Omit<Question, 'id' | 'created_at'>[] = [
  // 섹션 1
  {
    sort_order: 1,
    section_label: '섹션 1. 전반적 만족도',
    question_text: '오늘 체육대회에 전반적으로 얼마나 만족하셨나요?',
    question_type: 'scale',
    options: [],
    config: { size: 5, labels: ['매우 불만족', '불만족', '보통', '만족', '매우 만족'], required: true },
    is_active: true,
  },
  {
    sort_order: 2,
    section_label: '섹션 1. 전반적 만족도',
    question_text: '내년에도 참여하고 싶으신가요?',
    question_type: 'scale',
    options: [],
    config: { size: 5, labels: ['전혀 그렇지 않다', '그렇지 않다', '보통', '그렇다', '매우 그렇다'], required: true },
    is_active: true,
  },
  {
    sort_order: 3,
    section_label: '섹션 1. 전반적 만족도',
    question_text: '올해 체육대회, 한 마디로 표현한다면? (단어/짧은 문장)',
    question_type: 'text',
    options: [],
    config: {},
    is_active: true,
  },
  // 섹션 2
  {
    sort_order: 4,
    section_label: '섹션 2. 종목별 평가',
    question_text: '참여하거나 관람한 종목을 모두 체크해 주세요.',
    question_type: 'checkbox',
    options: EVENTS,
    config: { required: true },
    is_active: true,
  },
  {
    sort_order: 5,
    section_label: '섹션 2. 종목별 평가',
    question_text: '가장 재미있었던 것 최대 2개를 골라 주세요.',
    question_type: 'checkbox',
    options: EVENTS,
    config: { max: 2 },
    is_active: true,
  },
  {
    sort_order: 6,
    section_label: '섹션 2. 종목별 평가',
    question_text: '내년에는 없애거나 바꿔도 좋을 것 최대 2개를 골라 주세요.',
    question_type: 'checkbox',
    options: EVENTS,
    config: { max: 2 },
    is_active: true,
  },
  {
    sort_order: 7,
    section_label: '섹션 2. 종목별 평가',
    question_text: '내년에 추가했으면 하는 종목을 골라 주세요.',
    question_type: 'checkbox',
    options: ['발야구', '피구', '족구', '배드민턴', '줄다리기', '보드게임/실내 종목', '현재 종목 유지', '기타'],
    config: {},
    is_active: true,
  },
  // 섹션 3
  {
    sort_order: 8,
    section_label: '섹션 3. 운영 세부 평가',
    question_text: '다음 항목을 각각 5점 척도로 평가해 주세요.',
    question_type: 'matrix',
    options: [
      { key: 'mc', label: 'MC 진행 (최성필 MC)' },
      { key: 'lunch', label: '점심 도시락 (훈제오리/제육/함박)' },
      { key: 'foodtruck', label: '푸드트럭 및 생맥주' },
      { key: 'team', label: '팀 배정 (인원 구성 균형)' },
      { key: 'layout', label: '행사장 레이아웃 및 동선' },
      { key: 'cheer', label: '응원 분위기' },
      { key: 'gaon', label: '가온 놀이동산 스티커 경품 이벤트' },
    ] as MatrixItem[],
    config: { size: 5 },
    is_active: true,
  },
  {
    sort_order: 9,
    section_label: '섹션 3. 운영 세부 평가',
    question_text: '가온 놀이동산(에어바운스존/플레이존/이벤트존)을 이용하셨나요?',
    question_type: 'conditional',
    options: [],
    config: {
      trigger_options: ['이용 안 함', '이용함'],
      satisfaction_labels: ['불만족', '보통', '만족'],
      zones: ['에어바운스존', '플레이존', '이벤트존'],
      required: true,
    },
    is_active: true,
  },
  {
    sort_order: 10,
    section_label: '섹션 3. 운영 세부 평가',
    question_text: '행사 중 가장 불편하거나 아쉬웠던 점은?',
    question_type: 'checkbox',
    options: [
      '특정 종목 대기 시간이 너무 길었다',
      '내가 직접 참여할 종목이 부족했다',
      '팀 인원 불균형이 신경 쓰였다',
      '음식/음료 관련 불만',
      '동선이 불편했다',
      '날씨/환경 문제',
      '특별히 없다',
      '기타',
    ],
    config: {},
    is_active: true,
  },
  {
    sort_order: 11,
    section_label: '섹션 3. 운영 세부 평가',
    question_text: '올해 새로 도입된 여성 스테이지에 대한 의견을 선택해 주세요.',
    question_type: 'radio',
    options: ['불필요하다', '있어도 그만 없어도 그만', '좋았다, 유지했으면 한다', '더 확대했으면 한다'],
    config: { required: true },
    is_active: true,
  },
  // 섹션 4
  {
    sort_order: 12,
    section_label: '섹션 4. 내년 기획 인풋',
    question_text: '내년 체육대회에서 딱 한 가지만 바꿀 수 있다면 무엇을 바꾸고 싶으신가요?',
    question_type: 'textarea',
    options: [],
    config: {},
    is_active: true,
  },
  {
    sort_order: 13,
    section_label: '섹션 4. 내년 기획 인풋',
    question_text: '체육대회 외에 구성원 화합을 위해 해보고 싶은 행사 형식이 있다면?',
    question_type: 'checkbox',
    options: ['소규모 팀빌딩 워크샵', '문화 공연/스포츠 관람', '봉사활동', '소셜 다이닝/맛집 투어', '현재 방식 유지', '기타'],
    config: {},
    is_active: true,
  },
  // 섹션 5
  {
    sort_order: 14,
    section_label: '섹션 5. 응답자 분류',
    question_text: '소속 팀',
    question_type: 'radio',
    options: ['KING', 'ACE', 'ONE', 'NICE'],
    config: { required: true },
    is_active: true,
  },
  {
    sort_order: 15,
    section_label: '섹션 5. 응답자 분류',
    question_text: '성별',
    question_type: 'radio',
    options: ['남성', '여성', '응답 안 함'],
    config: { required: true },
    is_active: true,
  },
]
